[tool.bumpversion]
current_version = "0.1.0"
commit = true
tag = true
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = "{current_version}...{new_version}"

[[tool.bumpversion.files]]
filename = "docx_locker/__init__.py"
search = '__version__ = "{current_version}"'
replace = "{current_version}...{new_version}"
